######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 18 07:12:12 2010
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .
QT += network
CONFIG += debug_and_release
# Input
HEADERS += conn.h mwin.h
SOURCES += main.cc mwin.cc conn.cc
