<?php
/* Autogenerated file from the Alchemiestick CRM Unity installation */
date_default_timezone_set("America/Los_Angeles");
$cust_table = "customer";
$database = "unity";
$failed = false;
$order_path = "/var/ftp/unity";

function set_failed($link) {
    global $failed;
    $failed = true;
    mysql_close($link);
    return -1;
}

function dbcon()
{
	global $database, $failed;
	$link = mysql_connect("localhost","unity","dagobar") or die("connect... ". mysql_errno() .":". mysql_error());
	mysql_select_db($database,$link) or set_failed($link);
	if($failed) { $link = -1; $failed = false; }
	return $link;
}
?>
