<?php
session_start();
 
$ssl = "0";
if(isset($_SERVER["HTTPS"])) $ssl = "1";

$xml_conf = "<?xml version=\"1.0\" ?>
<config>
 <webhost>${_SERVER['SERVER_NAME']}</webhost>
 <apppath>${_SESSION['unity_app_path']}</apppath>
 <ssl>${ssl}</ssl>
 <ftphost>${_SESSION['v_ftp_host']}</ftphost>
 <ftpport>${_SESSION['v_ftp_port']}</ftpport>
 <ftppath>/</ftppath>
 <ftptmp>/tmp/</ftptmp>
 <ftpuser>".$_SESSION['v_ftp_user']."</ftpuser>
 <ftppass>".$_SESSION['v_ftp_pass']."</ftppass>
 <font_size>12</font_size>
</config>
";
file_put_contents("../app/config.xml", $xml_conf);    

$dbhost = $_SESSION['dbhost'];
$dbuser = $_SESSION['unity_db_user'];
$dbpass = $_SESSION['unity_db_pass'];

$admin_user = $_SESSION['crm_admin_user'];
$admin_pass = $_SESSION['crm_admin_pass'];
$admin_mail = $_SESSION['crm_admin_mail'];

$startdb_file = "<?php
/* Autogenerated file from the Alchemiestick CRM Unity installation */
date_default_timezone_set(\"${_SESSION['timezone']}\");
\$cust_table = \"${_SESSION['unity_ctable']}\";
\$database = \"${_SESSION['unity_db_name']}\";
\$failed = false;
\$order_path = \"${_SESSION['unity_ftp_path']}\";

function set_failed(\$link) {
    global \$failed;
    \$failed = true;
    mysql_close(\$link);
    return -1;
}

function dbcon()
{
	global \$database, \$failed;
	\$link = mysql_connect(\"${dbhost}\",\"${dbuser}\",\"${dbpass}\") or die(\"connect... \". mysql_errno() .\":\". mysql_error());
	mysql_select_db(\$database,\$link) or set_failed(\$link);
	if(\$failed) { \$link = -1; \$failed = false; }
	return \$link;
}
?>
";
 file_put_contents("../include/startdb.php", $startdb_file);    

$file = explode("\n", file_get_contents("unity_proto.sql"));
 $tmp = array();
 foreach( $file as $line ) {
    if(preg_match("/^--/", $line)) continue;
    $tmp[] = $line;
 }
 $tables = explode(";",implode(" ",$tmp));
 $tables[0] = str_replace("%%cust_table%%", "`".$_SESSION['unity_ctable'] ."`", $tables[0]);
 $tables[] = "insert into Bruger set brugernavn='${admin_user}',pass='". crypt($admin_pass) . "',brugernr=10,mail='${admin_mail}'";
 $tables[] = "insert into mail_rules set active='1',type='O',conditions='default',maillist='${admin_mail}'";
 
 $dbsetup = array();
 if(isset($_SESSION['force_db_creation']))
    $dbsetup[] = "drop database if exists `" . $_SESSION['unity_db_name'] . "`";
 $dbsetup[] = "create database if not exists `" . $_SESSION['unity_db_name'] . "`";
 $dbsetup[] = "grant all on `${_SESSION['unity_db_name']}`.* to '${dbuser}'@'${dbhost}' identified by '$dbpass'";
 
 $link = mysql_connect($dbhost,$_SESSION['dbuser'],$_SESSION['dbpass']);
 echo mysql_error($link) . "<br />\n";
 foreach ($dbsetup as $que) {
    mysql_query($que,$link);
    echo mysql_error($link) . "<br />\n";
 }
 mysql_select_db($_SESSION['unity_db_name'],$link);
 foreach ($tables as $que) {
    mysql_query($que,$link);
    echo mysql_error($link) . "<br />\n";
 }
mysql_close($link);
 
?>
<pre>
<?php print_r($_SESSION) ?>
</pre>
